### ISSUE TITLE
Older releases deleted

### ISSUE THREAD

**Issue by jamesrwhite** [trustpilot/python-trustpilot#1]
Hi,

You seem to have removed all historical releases from pypi and git, is this intentional? We were using v4.0.2 which seems to have vanished :(

**Comment by jamesrwhite** [comment]
You also seem to have various api keys and passwords publically visible in your travis config file which I'm pretty sure is not a good idea.

**Comment by sloev** [comment]
hi @jamesrwhite 
thanks for notifying us
the travis keys are encrypted using travis's public key and therefore not dangerous.
The releases where deleted deliberately , but upgrading to a current release should be an issue.
Sorry for ridiculous delay on this reply 🤦‍♂
