### ISSUE TITLE
Backend application authentication

### ISSUE THREAD

**Issue by JohnPaton** [trustpilot/python-trustpilot#13]
We're interested in making some API calls on a schedule from our server, but it seems (also from the [docs](https://developers.trustpilot.com/authentication)) that all authentication options require a personal account password. Is this true, or is there an API-key based auth option that I'm not seeing?

**Comment by sloev** [comment]
we have identified the issue and we are working on it.
sorry for taking so long to reply.
Will keep you updated on the progress made and mention you when the issue is fixed

**Comment by sloev** [comment]
@JohnPaton the issue should be fixed now, please check if its solved for you too. sorry for the latency

**Comment by JohnPaton** [comment]
@sloev do you have a link to the docs or something where I can see how it should work?

**Comment by sloev** [comment]
Sure. Sorry, forgot to mention.

This lib can take api tokens but you need to get them issued here:
https://documentation-apidocumentation.trustpilot.com/

**Comment by JohnPaton** [comment]
Great, I'll check it out!
