### ISSUE TITLE
Create session without secret

### ISSUE THREAD

**Issue by thomasemilhansen** [trustpilot/python-trustpilot#8]
The Trustpilot public api doesn't require a secret. Some users may thus use the client without having a secret. However, creating a session without a secret is not possible. The user has to set the secret to some string. It works with the empty string, but not None. It would be best if the user should not bother with the secret at all, if he/she hasn't got one.

**Comment by sloev** [comment]
Would you be able to help out? i can code review :-)

**Comment by thomasemilhansen** [comment]
ofc!

**Comment by sloev** [comment]
fix in https://github.com/trustpilot/python-trustpilot/pull/14
